### ISSUE TITLE
Bug: Not enqueuing JS on TML profile page in some cases.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-register-helper#135] opened 2019-01-18 19:55 UTC
It seems like the `method_exists('Theme_My_Login', 'is_tml_page')` is returning false in a support user's case, even though it's used successfully in the same line. I'm unable to recreate this but (`class_exists("Theme_My_Login") && Theme_My_Login::is_tml_page("profile") ` fixed it.

https://github.com/strangerstudios/pmpro-register-helper/blob/c0be483e7416e30c8e1dc74fadcb145b040d0d48/pmpro-register-helper.php#L1240

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/rich-text-editor-for-register-helper-textarea/

**Comment by pointydrip** [comment] 2020-02-24 14:36
@messica Did you find a solution to this? I a pmpro customer and I have select2 options that are unusable from the TML profile page as a result...

**Comment by andrewlimaza** [comment] 2020-04-24 09:01
I have just tested this and it works as intended. I am testing with a pre-release that includes an updated version of select2.js (which I think TML bundles as well).

You can test it by downloading the 'dev' branch of this repository.

**Comment by andrewlimaza** [comment] 2020-04-24 09:16
This has been fixed in upcoming release - https://github.com/strangerstudios/pmpro-register-helper/blob/dev/pmpro-register-helper.php#L1307-L1308

**Closed by andrewlimaza** 2020-04-24 09:16 UTC
Labels: Blocking Next Release, Difficulty: Easy
