### ISSUE TITLE
Conditional 'depends' required fields apply even when not visible

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/pmpro-register-helper#116] opened 2018-02-24 21:21 UTC
Seems that the requiredness of depends fields is also applying to conditions that don't match the depends clause and prevent registration because the fields can't be seen.

https://www.paidmembershipspro.com/forums/topic/adding-fields-to-the-membership-form/#post-142720

**Comment by dparker1005** [comment] 2020-10-06 18:27
I am going to close this Issue as it is a duplicate of https://github.com/strangerstudios/pmpro-register-helper/issues/70. If you would like to discuss this behavior further, please feel free to follow up on that original issue.

**Closed by dparker1005** 2020-10-06 18:27 UTC
