### ISSUE TITLE
Dependent field still required when not used

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-register-helper#162] opened 2020-02-19 17:25 UTC
If you set the dependent field to required – then it’s always required even when it’s not shown

**Comment by andrewlimaza** [comment] 2020-04-23 11:59
This would require a bit of code workaround to get working. For now you may use custom JavaScript to add a 'required' attribute to the field when showing it and set the default value for required to be false.

Going to push this back to 1.7 release.

**Comment by andrewlimaza** [comment] 2020-04-23 12:09
Closing this thread, it's a duplicate of this one - https://github.com/strangerstudios/pmpro-register-helper/issues/141

**Closed by andrewlimaza** 2020-04-23 12:09 UTC
