### ISSUE TITLE
Conditional Fields and Required attribute not working as intended

### ISSUE THREAD

**Issue by salihkulangara** [strangerstudios/pmpro-register-helper#141] opened 2019-04-25 06:07 UTC
I am using PMPRO with Register Helper add on, I have created a conditional field like this:
`$fields[] = new PMProRH_Field(
    'profession',
    'radio', // type of field
    	array(
        'options' =>
            array(
                'Judge' => 'Judge',
                'Attorney' => 'Attorney',
                'Social Worker' => 'Social Worker',
                'Attorney & Social Worker' => 'Attorney & Social Worker',
                'Other' => 'Other'
            ),
        'label'=>'Profession',
        'required'=>true,
	'profile'	=> true,
  	)
    );
	$fields[] = new PMProRH_Field(
            "other_profession",
             "textarea",
              array(
		"depends"=>array(array('id' => "profession", 'value' => "Other")),
		"label"=>"Please Specify Other",
		'profile'	=> true,
                 'required'=>true,
        ));`

The dependent field("please specify other" field) should be required only if the “other” option selected from the “Profession”. If I give ‘required’=>true to “other_profession”(Please Specify Other) this dependent field will be always be required, and even if I don’t select other option from “Profession” I get required field error when submit the form(the field will be hidden). Is there any option I am missing, or this is a bug?

**Comment by andrewlimaza** [comment] 2019-04-25 08:04
Thanks for this, I have replied to your thread on .org.

We do need to resolve this as it is a minor bug with the depends field.

**Comment by salihkulangara** [comment] 2019-04-25 08:23
Thanks, and waiting for a fix from your end in the next update itself :)

**Comment by dparker1005** [comment] 2020-10-06 18:45
I am closing this thread as it is a duplicate of #70. Please feel free to comment on that original issue if you would like to discuss this further.

**Closed by dparker1005** 2020-10-06 18:45 UTC
